### ISSUE TITLE
Remove hard coded submariner namespace

### ISSUE THREAD

**Issue by Negashev** [rancher/submariner#12]
Can we remove hard coded namespace?
https://github.com/rancher/submariner/blob/4153f762a21ea9b554166ad424faaae4162cd769/main.go#L160

**Comment by m4ce** [comment]
same here.

**Comment by vthapar** [comment]
+1 to this.

**Comment by mangelajo** [comment]
What's the intent/benefit behind this?

**Comment by Negashev** [comment]
@mangelajo The goal is to run a submariner in any namespace, as for example the rancher multicluster app

**Comment by m4ce** [comment]
We had to change the namespace as we run submariner in an unsupported way to overcome the multi-AZ routing limitation (see https://github.com/rancher/submariner/issues/16). This involves running multiple brokers which have to end up in different namespaces.
