### ISSUE TITLE
Submariner Broker Url is a private IP. When we change it to the public IP of the instance, we get this error.

### ISSUE THREAD

**Issue by sagargulabanicldcvr** [rancher/submariner#5]
I have setup a broker and and one other cluster on AWS.
When I get the submariner broker url using this command.

SUBMARINER_BROKER_URL=$(kubectl -n default get endpoints kubernetes -o jsonpath="{.subsets[0].addresses[0].ip}:{.subsets[0].ports[0].port}")

It returns a private address.
So I changed this to the public address of the instance.

However on running the submariner commands on one of the cluster,
I see that this pod has gone into error state submariner-b9644d584-kr7ks.

When I check the logs of this pod, I get the following there.

I0325 15:03:08.685347       1 datastoresyncer.go:78] Ensuring we are the only endpoint active for this cluster
F0325 15:03:08.698528       1 datastoresyncer.go:81] Error while retrieving endpoints Get https://52.221.253.20:443/apis/submariner.io/v1/namespaces/submariner-k8s-broker/endpoints: x509: certificate is valid for 101.64.0.1, 127.0.0.1, not 52.221.253.20
goroutine 49 [running]:
github.com/rancher/submariner/vendor/k8s.io/klog.stacks(0xc000290500, 0xc0004dc000, 0xfe, 0x204)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:828 +0xd4
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).output(0x1df5a60, 0xc000000003, 0xc0001100b0, 0x1d874a7, 0x12, 0x51, 0x0)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:779 +0x306
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).printf(0x1df5a60, 0x3, 0x125f2a6, 0x23, 0xc0003bfac8, 0x1, 0x1)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/rancher/submariner/vendor/k8s.io/klog.Fatalf(0x125f2a6, 0x23, 0xc0003bfac8, 0x1, 0x1)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:1207 +0x67
github.com/rancher/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).ensureExclusiveEndpoint(0xc0003f1180)
	/go/src/github.com/rancher/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:81 +0x968
github.com/rancher/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).Run(0xc0003f1180, 0xc00008a6c0, 0x0, 0x0)
	/go/src/github.com/rancher/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:139 +0x2af
main.main.func1.3(0xc00041a6f0, 0xc0003f1180, 0xc00008a6c0, 0xc0004302b0)
	/go/src/github.com/rancher/submariner/main.go:132 +0x63
created by main.main.func1
	/go/src/github.com/rancher/submariner/main.go:130 +0xb63
00[DMN] signal of type SIGTERM received. Shutting down

**Comment by Oats87** [comment]
How did you provision your broker cluster? If using RKE, you should have a config file which has nodes that contain both the internal/external address of the node, otherwise the certificates will not contain the node's public IP in the list of SAN's. You can also do this through https://rancher.com/docs/rke/v0.1.x/en/config-options/authentication/ where you specify the SAN for the api server, which gets behavior that is similar.

If you are using a different cluster type, I would look at the documentation for that installer and see if you can figure out how to add the node's public IP.

**Comment by sagargulabanicldcvr** [comment]
No I have not used RKE. I have used kops on AWS for this.

**Comment by sagargulabanicldcvr** [comment]
ok I pointed it to the load balancer of the server and I was able to resolve it . Thanks
